Part A: Read the Dataset and Perform EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [10]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [11]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [12]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Part B: Identify Nominal, Numeric and Binary Attributes

In [13]:
print("Columns in the dataset:")
print(df.columns)

Columns in the dataset:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [14]:
Nominal = ['Name', 'Ticket', 'Cabin', 'Embarked']

Numeric = ['PassengerId', 'Age', 'Fare', 'SibSp', 'Parch', 'Pclass']

Binary = ['Survived', 'Sex']

print("Nominal Attributes:", Nominal)
print("Numeric Attributes:", Numeric)
print("Binary Attributes:", Binary)

Nominal Attributes: ['Name', 'Ticket', 'Cabin', 'Embarked']
Numeric Attributes: ['PassengerId', 'Age', 'Fare', 'SibSp', 'Parch', 'Pclass']
Binary Attributes: ['Survived', 'Sex']

Part C: Data Dissimilarity for Two Nominal Attributes

In [15]:
df[['Sex', 'Embarked']].head()

      Sex Embarked
0    male        S
1  female        C
2  female        S
3  female        S
4    male        S

In [16]:
p1 = df.loc[0, ['Sex', 'Embarked']]
p2 = df.loc[1, ['Sex', 'Embarked']]

matches = (p1 == p2).sum()
total = len(p1)
dissimilarity = 1 - (matches / total)

print("Passenger 1:")
print(p1)

print("\nPassenger 2:")
print(p2)

print("\nDissimilarity =", dissimilarity)

Passenger 1:
Sex         male
Embarked       S
Name: 0, dtype: object

Passenger 2:
Sex         female
Embarked         C
Name: 1, dtype: object

Dissimilarity = 1.0

Part D: Data Dissimilarity for Two Numeric Attributes

In [17]:
df[['Age', 'Fare']].head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [18]:
import math

p1 = df.loc[0, ['Age', 'Fare']]
p2 = df.loc[1, ['Age', 'Fare']]

distance = math.sqrt(((p1 - p2) ** 2).sum())

print("Passenger 1:")
print(p1)

print("\nPassenger 2:")
print(p2)

print("\nEuclidean Distance =", distance)

Passenger 1:
Age     22.0
Fare    7.25
Name: 0, dtype: object

Passenger 2:
Age        38.0
Fare    71.2833
Name: 1, dtype: object

Euclidean Distance = 66.00199624928021